/*
  Warnings:

  - The values [EIGHT_NINE,EIGHT_TEN,EIGHT_TWELVE,NINE_TEN,TEN_ELEVEN,TEN_TWELVE,ELEVEN_TWELVE,TWELVE_THIRTEEN,TWELVE_FOURTEEN,TWELVE_SIXTEEN,THIRTEEN_FOURTEEN,FOURTEEN_FIFTEEN,FOURTEEN_SIXTEEN,FIFTEEN_SIXTEEN,SIXTEEN_SEVENTEEN,SIXTEEN_TWENTY,SEVENTEEN_EIGHTEEN,EIGHTEEN_NINETEEN,EIGHTEEN_TWENTY,NINETEEN_TWENTY] on the enum `TimeSlot` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "TimeSlot_new" AS ENUM ('EIGHT_ELEVEN', 'ELEVEN_FOURTEEN', 'FOURTEEN_SEVENTEEN', 'SEVENTEEN_TWENTY');
ALTER TABLE "Order" ALTER COLUMN "timeSlot" TYPE "TimeSlot_new" USING ("timeSlot"::text::"TimeSlot_new");
ALTER TYPE "TimeSlot" RENAME TO "TimeSlot_old";
ALTER TYPE "TimeSlot_new" RENAME TO "TimeSlot";
DROP TYPE "TimeSlot_old";
COMMIT;
